on:
  push:
    branches:
      - "**"
    tags:
      - "**"

jobs:
  call-publish:
    uses: ./.github/workflows/build-and-publish.yaml
    permissions:
      contents: write      # attest-build-provenance (read), action-gh-release (write)
      id-token: write      # attest-build-provenance
      attestations: write  # attest-build-provenance
    with:
      binary-name: workflow-test
      test-reproducibility: false
      cargo-verbose: true
